DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL,
MATRICULA VARCHAR(25) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES(DEFAULT,'LUIS','MARTINEZ','12345');